import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { articleInput } from "@/test/factories";
import { createArticle, publishArticle, updateArticle, unpublishArticle, applyTranslationToPublishedRevision, getArticleRevisionById } from "@/lib/services/articles";
import { getDb, closeDb } from "@/lib/db/connection";
import { migrate } from "@/lib/db/migrate";
import { ensurePublicationProofRecord, createPublicationProof, advanceOpenTimestampProof, captureWaybackProof, getPublicationProof, listPublicPublicationProofPage } from "@/lib/services/publication-proofs";
import { isArticleProofEligible, isPublicationProofEligible } from "@/lib/services/proof-eligibility";
import { createJobHandlers } from "@/lib/jobs/handlers";
import { enqueueJob, runNextJob } from "@/lib/jobs/queue";
import { reconcileUnfinishedProofs } from "@/lib/jobs/reconcile";

let tmpDir: string;
beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "arthurs-review-life-proofs-"));
  process.env.DATA_DIR = tmpDir;
  process.env.SITE_URL = "http://localhost:3000";
  closeDb(); migrate();
});
afterEach(() => { closeDb(); fs.rmSync(tmpDir, { recursive: true, force: true }); });

function publish(category: "life" | "commentary" = "commentary") {
  return publishArticle(createArticle(articleInput({ category })).id);
}

function legacyLifeProof() {
  const article = publish();
  const proof = ensurePublicationProofRecord(article)!;
  // Emulate a proof generated by the old app for an immutable life revision.
  getDb().prepare("update article_revisions set category = 'life' where id = ?").run(article.revisionId);
  getDb().prepare("update publication_proofs set public_url = ? where id = ?").run(`http://localhost:3000/life/${article.slug}`, proof.id);
  return { article: { ...article, category: "life" as const }, proof: getPublicationProof(proof.id)! };
}

describe("life publication-proof exclusion", () => {
  it("never queues proofs for publishing, editing, translating or republishing life", async () => {
    let article = publish("life");
    article = updateArticle(article.id, articleInput({ category: "life", bodyZh: "新的照片说明" }), article.draftRevisionId);
    article = publishArticle(article.id);
    expect(applyTranslationToPublishedRevision(article.id, article.revisionId, {
      titleEn: "Life", excerptEn: "Photos", bodyEn: "A photo caption",
    }).status).toBe("published");
    unpublishArticle(article.id);
    article = publishArticle(article.id);
    expect(getDb().prepare("select count(*) as total from jobs where type = 'proof.create'").get()).toEqual({ total: 0 });
    expect(getDb().prepare("select distinct type from jobs order by type").all()).toEqual([{ type: "cache.invalidate" }, { type: "search.embed" }]);
    const stamp = vi.fn(async () => Uint8Array.of(1));
    const capture = vi.fn(async () => "https://web.archive.org/example");
    expect(ensurePublicationProofRecord(article)).toBeNull();
    expect(await createPublicationProof(article, { now: () => new Date(), stamp, capture })).toBeNull();
    expect(stamp).not.toHaveBeenCalled(); expect(capture).not.toHaveBeenCalled();
    expect(getDb().prepare("select count(*) as total from publication_proofs").get()).toEqual({ total: 0 });
  });

  it("ignores a life draft but blocks old text tasks once life is published", () => {
    const article = publish();
    const proof = ensurePublicationProofRecord(article)!;
    updateArticle(article.id, articleInput({ category: "life" }), article.draftRevisionId);
    expect(isArticleProofEligible(article)).toBe(true);
    expect(isPublicationProofEligible(proof.id)).toBe(true);
    publishArticle(article.id);
    expect(isArticleProofEligible(article)).toBe(false);
    expect(isPublicationProofEligible(proof.id)).toBe(false);
    expect(ensurePublicationProofRecord(article)).toBeNull();
  });

  it("preserves old proofs and downloads while skipping all evidence services", async () => {
    const { article, proof } = legacyLifeProof();
    const bytes = fs.readFileSync(path.join(tmpDir, proof.documentPath));
    const receiptPath = `${proof.documentPath}.ots`;
    fs.writeFileSync(path.join(tmpDir, receiptPath), Uint8Array.of(3, 4));
    getDb().prepare("update publication_proofs set ots_path = ? where id = ?").run(receiptPath, proof.id);
    const before = getPublicationProof(proof.id);
    const stamp = vi.fn(async () => Uint8Array.of(1));
    const capture = vi.fn(async () => "https://web.archive.org/example");
    expect(await advanceOpenTimestampProof(proof.id, { now: () => new Date(), stamp, capture })).toBeNull();
    expect(await captureWaybackProof(proof.id, capture)).toBeNull();
    expect(getPublicationProof(proof.id)).toEqual(before);
    expect(fs.readFileSync(path.join(tmpDir, proof.documentPath))).toEqual(bytes);
    expect(listPublicPublicationProofPage()).toMatchObject({ totalArticles: 1, totalProofs: 1 });
    expect(listPublicPublicationProofPage().items[0].articleCategory).toBe("life");
    for (const kind of ["source", "ots"]) {
      const route = kind === "source" ? await import("@/app/proofs/[id]/source/route") : await import("@/app/proofs/[id]/ots/route");
      const response = await route.GET(new Request("http://localhost"), { params: Promise.resolve({ id: String(proof.id) }) });
      expect(response.status).toBe(200);
    }
    expect(stamp).not.toHaveBeenCalled(); expect(capture).not.toHaveBeenCalled();
    expect(isArticleProofEligible(article)).toBe(false);
  });

  it("continues to skip an original life proof after moving the article back to text, including legacy URL-only records", () => {
    const { article, proof } = legacyLifeProof();
    updateArticle(article.id, articleInput({ category: "commentary" }), article.draftRevisionId);
    const text = publishArticle(article.id);
    expect(isArticleProofEligible(text)).toBe(true);
    expect(isPublicationProofEligible(proof.id)).toBe(false);
    getDb().prepare("update publication_proofs set article_revision_id = null where id = ?").run(proof.id);
    expect(isPublicationProofEligible(proof.id)).toBe(false);
    expect(ensurePublicationProofRecord(text)).not.toBeNull();
  });

  it("retires queued, running and dead life tasks at worker startup without changing proof records", () => {
    const { article, proof } = legacyLifeProof();
    getDb().prepare("delete from jobs").run();
    enqueueJob({ type: "proof.create", payload: { articleId: article.id, revisionId: article.revisionId, publishedAt: article.publishedAt, updatedAt: article.updatedAt }, dedupeKey: "old-life-create" });
    const ots = enqueueJob({ type: "proof.ots_upgrade_verify", payload: { proofId: proof.id }, dedupeKey: `proof:${proof.id}` });
    const wayback = enqueueJob({ type: "proof.wayback_capture", payload: { proofId: proof.id }, dedupeKey: `proof:${proof.id}` });
    getDb().prepare("update jobs set status = 'running', locked_by = 'old-worker' where id = ?").run(ots.id);
    getDb().prepare("update jobs set status = 'dead' where id = ?").run(wayback.id);
    expect(reconcileUnfinishedProofs()).toEqual({ ots: 0, wayback: 0 });
    expect(reconcileUnfinishedProofs()).toEqual({ ots: 0, wayback: 0 });
    expect(getDb().prepare("select distinct status from jobs").all()).toEqual([{ status: "succeeded" }]);
    expect(getPublicationProof(proof.id)).toEqual(proof);
  });

  it("finishes already-queued life jobs as skipped without calling service dependencies", async () => {
    const { article, proof } = legacyLifeProof();
    getDb().prepare("delete from jobs").run();
    const ensure = vi.fn(), advance = vi.fn(), capture = vi.fn();
    const handlers = createJobHandlers({ ensurePublicationProofRecord: ensure, advanceOpenTimestampProof: advance, captureWaybackProof: capture });
    enqueueJob({ type: "proof.create", payload: { articleId: article.id, revisionId: article.revisionId, publishedAt: article.publishedAt, updatedAt: article.updatedAt }, dedupeKey: "life-create" });
    enqueueJob({ type: "proof.ots_upgrade_verify", payload: { proofId: proof.id }, dedupeKey: `proof:${proof.id}` });
    enqueueJob({ type: "proof.wayback_capture", payload: { proofId: proof.id }, dedupeKey: `proof:${proof.id}` });
    for (let index = 0; index < 3; index += 1) {
      expect(await runNextJob({ workerId: "test", handlers })).toMatchObject({ status: "succeeded" });
    }
    expect(ensure).not.toHaveBeenCalled(); expect(advance).not.toHaveBeenCalled(); expect(capture).not.toHaveBeenCalled();
    expect(getArticleRevisionById(article.id, article.revisionId)?.category).toBe("life");
    expect(getPublicationProof(proof.id)).toEqual(proof);
  });

  it("skips life in the actual replay and backfill commands without modifying existing evidence", () => {
    const { proof } = legacyLifeProof();
    const replay = execFileSync(process.execPath, ["--import", "tsx", "scripts/replay-proof.ts", String(proof.id)], {
      encoding: "utf8", env: { ...process.env, DATA_DIR: tmpDir },
    });
    expect(JSON.parse(replay)).toMatchObject({ id: proof.id, skipped: true, reason: expect.stringContaining("Life posts") });
    execFileSync(process.execPath, ["--import", "tsx", "scripts/backfill-publication-proofs.ts"], {
      env: { ...process.env, DATA_DIR: tmpDir },
    });
    expect(getPublicationProof(proof.id)).toEqual(proof);
    expect(getDb().prepare("select count(*) as total from publication_proofs").get()).toEqual({ total: 1 });
  });
});
